INSERT INTO tags (name) VALUES ('Inspiration') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Nature') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Love') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Friendship') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Adventure') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Fantasy') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Mystery') ON CONFLICT DO NOTHING;
INSERT INTO tags (name) VALUES ('Humor') ON CONFLICT DO NOTHING;